# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          environment:
            FLASK_APP: hello.py
          command: |
            . venv/bin/activate

            # Background flask app
            coverage run \
              --parallel-mode \
              -m flask run &> /tmp/flask.log &
            sleep 1
            set -x
            jobs
            cat /tmp/flask.log

            # Run a blackbox test -- for simplicity just curl an endpoint
            curl http://127.0.0.1:5000/

            # Stop the background jump: coverage.py running flask
            jobs -p | xargs kill -INT
            sleep 1
            ls -lah
            set +x

            # Covert coverage.py into Cobertura.xml report
            coverage xml

            # Upload to codecov
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
